#pragma once

#define PACMAN_WORLD_SMALL 0
#define PACMAN_WORLD_LARGE 1

#define PACMAN_WORLD_SIZE PACMAN_WORLD_SMALL

//#define PACMAN_ADRENO_PROFILER_COMPATIBILITY

#define PACMAN_DEBUG_MAP_TEXTURE